version: 2

builds:
  - binary: tasks
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

archives:
  - format: tar.gz

brews:
  - name: tasks
    homepage: https://github.com/PriyabrataMo/tasks
    description: A simple CLI for task management
    license: MIT
    tap:
      owner: PriyabrataMo
      repo: homebrew-tasks
    commit_author:
      name: Priyabrata
      email: priyabrata8558@gmail.com

checksum:
  name_template: 'checksums.txt'
