builds:
  - binary: tasks
    goos:
      - darwin
      - linus
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: tasks
    homepage: https://github.com/PriyabrataMo/tasks-cli
    tap:
      owner: tasks
      name: homebrew-tasks
    commit_author:
      name: Priyabrata
      email: priyabrata8558@gmail.com

checksum:
  name_template: 'checksums.txt'